In [1]:
import pandas as pd     # --- Part 1: Pandas ---
import numpy as np 

df = pd.read_csv("SGJobData.csv")
df.head()

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
0,"[{""id"":13,""category"":""Environment / Health""},{...",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,...,NaN,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0
1,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,...,NaN,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,Monthly,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0
2,"[{""id"":33,""category"":""Repair and Maintenance""}]",Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,...,NaN,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,Monthly,0,Closed,Senior Technician,4200.0
3,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,...,NaN,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,Monthly,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0
4,"[{""id"":2,""category"":""Admin / Secretarial""}]",Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,...,NaN,Non-executive,EATZ CATERING SERVICES PTE. LTD.,3400,2400,Monthly,0,Closed,Sales / Admin Cordinator,2900.0

In [ ]:
# checking size and type of the dataset
print(df.shape)

df.info()

(1048585, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048585 entries, 0 to 1048584
Data columns (total 22 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1048585 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1048585 non-null  int64
 8   metadata_totalNumberJobApplication  1048585 non-null  int64
 9   metadata_totalNumberOfView          1048585 non-null  int64
 10  minimumYearsExperience              1048585 non-null  int64
 11  numberOfVacancies                   1048585 non-null  int64
 12  occupationId                        0 non-null        float64
 13  positionLevels                      1044597 non-null  object
 14  postedCompany_name                  1044597 non-null  object
 15  salary_maximum                      1048585 non-null  int64
 16  salary_minimum                      1048585 non-null  int64
 17  salary_type                         1044597 non-null  object
 18  status_id                           1048585 non-null  int64
 19  status_jobStatus                    1044597 non-null  object
 20  title                               1044597 non-null  object
 21  average_salary                      1048585 non-null  float64
dtypes: bool(1), float64(2), int64(8), object(11)
memory usage: 169.0+ MB

In [ ]:
# checking values in the dataset
print("\nOccupation IDs:")
print(df["occupationId"].value_counts())

print("\nPosition Levels:")
print(df["positionLevels"].value_counts())

print("\nSalary Maximum:")
print(df["salary_maximum"].value_counts())

print("\nSalary Minimum:")
print(df["salary_minimum"].value_counts())

Occupation IDs:
Series([], Name: occupationId, dtype: int64)

Position Levels:
Executive            253701
Junior Executive     167656
Non-executive        131608
Fresh/entry level    118661
Professional         112208
Manager              110122
Senior Executive     100459
Middle Management     27375
Senior Management     22807
Name: positionLevels, dtype: int64

Salary Maximum:
5000        86521
4000        71302
3500        71161
4500        65420
6000        56530
            ...
2190            1
2471            1
20666           1
8030            1
14420727        1
Name: salary_maximum, Length: 2621, dtype: int64

Salary Minimum:
3000      145381
2500       97674
4000       70221
3500       66359
2000       66182
           ...
10883          1
7369           1
955            1
10465          1
164428         1
Name: salary_minimum, Length: 2138, dtype: int64

In [ ]:
# checking statistic of number type columns
df.describe()

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,occupationId,salary_maximum,salary_minimum,status_id,average_salary
count,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,1.048585e+06,0.0,1.048585e+06,1.048585e+06,1048585.0,1.048585e+06
mean,5.472327e-02,2.136571e+00,2.674536e+01,2.779573e+00,2.680043e+00,NaN,5.723578e+03,3.815312e+03,0.0,4.769445e+03
std,2.822675e-01,1.062612e+01,8.262001e+01,2.537049e+00,1.124301e+01,NaN,5.018387e+04,3.172182e+03,0.0,2.547809e+04
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.0,0.000000e+00
25%,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,NaN,3.300000e+03,2.500000e+03,0.0,2.900000e+03
50%,0.000000e+00,0.000000e+00,4.000000e+00,2.000000e+00,1.000000e+00,NaN,4.500000e+03,3.000000e+03,0.0,3.800000e+03
75%,0.000000e+00,1.000000e+00,1.700000e+01,4.000000e+00,2.000000e+00,NaN,6.500000e+03,4.500000e+03,0.0,5.500000e+03
max,2.000000e+00,1.342000e+03,8.190000e+03,8.800000e+01,9.990000e+02,NaN,2.533000e+07,3.500000e+05,0.0,1.266640e+07

In [2]:
# convert to non-scientific notation for better readability
pd.set_option('display.float_format', lambda x: '%.2f' % x)
print(df["salary_maximum"].describe())

df.describe()

count    1048585.00
mean        5723.58
std        50183.87
min            0.00
25%         3300.00
50%         4500.00
75%         6500.00
max     25330000.00
Name: salary_maximum, dtype: float64

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,occupationId,salary_maximum,salary_minimum,status_id,average_salary
count,1048585.00,1048585.00,1048585.00,1048585.00,1048585.00,0.00,1048585.00,1048585.00,1048585.00,1048585.00
mean,0.05,2.14,26.75,2.78,2.68,NaN,5723.58,3815.31,0.00,4769.45
std,0.28,10.63,82.62,2.54,11.24,NaN,50183.87,3172.18,0.00,25478.09
min,0.00,0.00,0.00,0.00,0.00,NaN,0.00,0.00,0.00,0.00
25%,0.00,0.00,1.00,1.00,1.00,NaN,3300.00,2500.00,0.00,2900.00
50%,0.00,0.00,4.00,2.00,1.00,NaN,4500.00,3000.00,0.00,3800.00
75%,0.00,1.00,17.00,4.00,2.00,NaN,6500.00,4500.00,0.00,5500.00
max,2.00,1342.00,8190.00,88.00,999.00,NaN,25330000.00,350000.00,0.00,12666400.00

In [ ]:
# checking object type columns
df.describe(include=object)

,categories,employmentTypes,metadata_expiryDate,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,positionLevels,postedCompany_name,salary_type,status_jobStatus,title
count,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597,1044597
unique,21125,8,453,1044597,431,603,9,53151,1,3,377084
top,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-07-28,MCF-2023-0252866,2023-06-09,2023-07-14,Executive,THE SUPREME HR ADVISORY PTE. LTD.,Monthly,Open,SUPERVISOR
freq,92869,458139,4487,1,4508,4029,253701,61638,1044597,902614,8331

In [3]:
# copy dataframe to a new variable for cleaning and analysis
dfcopy = df.copy()
dfcopy = dfcopy.drop(["occupationId", "status_id", "salary_type"], axis=1) # dropping columns that are not needed for analysis

In [4]:
# convert any relevant date columns from object to date format with coerce to handle any invalid date formats
date_columns = ["metadata_expiryDate", "metadata_newPostingDate", "metadata_originalPostingDate"]
dfcopy[date_columns] = dfcopy[date_columns].apply(pd.to_datetime, errors='coerce')

dfcopy.info() # checking the data types after conversion

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048585 entries, 0 to 1048584
Data columns (total 19 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  datetime64[ns]
 3   metadata_isPostedOnBehalf           1048585 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  datetime64[ns]
 6   metadata_originalPostingDate        1044597 non-null  datetime64[ns]
 7   metadata_repostCount                1048585 non-null  int64
 8   metadata_totalNumberJobApplication  1048585 non-null  int64
 9   metadata_totalNumberOfView          1048585 non-null  int64
 10  minimumYearsExperience              1048585 non-null  int64
 11  numberOfVacancies                   1048585 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1048585 non-null  int64
 15  salary_minimum                      1048585 non-null  int64
 16  status_jobStatus                    1044597 non-null  object
 17  title                               1044597 non-null  object
 18  average_salary                      1048585 non-null  float64
dtypes: bool(1), datetime64[ns](3), float64(1), int64(7), object(7)
memory usage: 145.0+ MB

In [ ]:
# checking column ""metadata_newPostingDate""
# to show earliest data from "metadata_newPostingDate"
earliest = dfcopy[
    (dfcopy["metadata_newPostingDate"].dt.year == 2023)
    & (dfcopy["metadata_newPostingDate"].dt.month < 3)]

earliest

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,positionLevels,postedCompany_name,salary_maximum,salary_minimum,status_jobStatus,title,average_salary
1048582,"[{""id"":2,""category"":""Admin / Secretarial""},{""i...",Contract,2023-08-16,False,RANDOM_JOB_20251115011348901570_7,2023-02-24,2023-01-26,1,580,3912,56,505,Executive,MINDFLEX EDUCATION PTE. LTD.,13798518,260117,Re-open,Social media content creator,7029317.50

In [ ]:
# EDA 1: checking any missing values in the dataset
print("\nMissing Values:")
print(dfcopy.isna().sum())

Missing Values:
categories                               3988
employmentTypes                          3988
metadata_expiryDate                      3988
metadata_isPostedOnBehalf                   0
metadata_jobPostId                       3988
metadata_newPostingDate                  3988
metadata_originalPostingDate             3988
metadata_repostCount                        0
metadata_totalNumberJobApplication          0
metadata_totalNumberOfView                  0
minimumYearsExperience                      0
numberOfVacancies                           0
occupationId                          1048585
positionLevels                           3988
postedCompany_name                       3988
salary_maximum                              0
salary_minimum                              0
salary_type                              3988
status_id                                   0
status_jobStatus                         3988
title                                    3988
average_salary                              0
dtype: int64

In [ ]:
# EDA 1: display the rows with missing values to check any patterns or issues in the dataset
missing_rows = df[dfcopy["positionLevels"].isna()]
missing_rows

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
197478,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
197480,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
197485,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
197488,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
197502,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606668,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
606670,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
606678,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
606695,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00
606701,NaN,NaN,NaN,False,NaN,NaN,NaN,0,0,0,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0.00

In [5]:
# EDA1: drop rows where positionLevels is NaN
dfcopy = dfcopy.dropna(subset=["positionLevels"])

print("missing positionLevels before: ", df["positionLevels"].isna().sum())
print("missing positionLevels after: ", dfcopy["positionLevels"].isna().sum())

print("shape before: ", df.shape)
print("shape after: ", dfcopy.shape)

missing positionLevels before:  3988
missing positionLevels after:  0
shape before:  (1048585, 22)
shape after:  (1044597, 19)

In [ ]:
# EDA 2: handling duplicate rows in the dataset
print("Number of duplicate rows before: ", dfcopy.duplicated().sum())

Number of duplicate rows before:  0

In [ ]:
# EDA 3: handling impossible values in the dataset, for possible negative amount
amt_columns = ["salary_maximum", "salary_minimum", "metadata_repostCount",
               "metadata_totalNumberJobApplication", "metadata_totalNumberOfView",
               "minimumYearsExperience","numberOfVacancies"]
negative_values = dfcopy[amt_columns][(dfcopy[amt_columns] < 0).any(axis=1)]
print("Negative values found:" , negative_values.sum())

Negative values found: salary_maximum                       0.00
salary_minimum                       0.00
metadata_repostCount                 0.00
metadata_totalNumberJobApplication   0.00
metadata_totalNumberOfView           0.00
minimumYearsExperience               0.00
numberOfVacancies                    0.00
dtype: float64

In [ ]:
# EDA3: checking values in column "numberofVacancies"
print(dfcopy["numberOfVacancies"].describe())
a = dfcopy["numberOfVacancies"].unique()
a.sort()
print(a)

dfcopy.loc[dfcopy["numberOfVacancies"] == 845, ["positionLevels", "numberOfVacancies", "status_jobStatus"]]

dfcopy["numberOfVacancies"].sum() # total number of vacancies in the dataset

dfcopy[["numberOfVacancies","metadata_repostCount","metadata_totalNumberJobApplication"]].sum() # total number of reposts in the dataset

count   1044597.00
mean          2.69
std          11.26
min           1.00
25%           1.00
50%           1.00
75%           2.00
max         999.00
Name: numberOfVacancies, dtype: float64
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  48  49  50  51  54  55  57  58  59
  60  62  64  65  67  69  70  80  86  88  90  98  99 100 101 102 103 108
 110 111 119 120 121 123 133 140 150 155 163 165 200 201 202 204 224 250
 291 300 302 328 400 499 500 505 510 579 682 693 845 900 902 998 999]

numberOfVacancies                     2810253
metadata_repostCount                    57382
metadata_totalNumberJobApplication    2240376
dtype: int64

In [ ]:
# EDA3: checking values in column "average_salary"
# checking data thru percentile
# dfcopy.loc[dfcopy["salary_maximum"] == 25330000 , ["positionLevels", "numberOfVacancies", "status_jobStatus","salary_maximum","salary_minimum","average_salary"]]
# dfcopy["salary_minimum"].describe(percentiles=[0.25, 0.5, 0.75, 0.90, 0.99])

dfcopy["average_salary"].describe(percentiles=[0.01, 0.02, 0.96, 0.97, 0.98, 0.99])

count    1048585.00
mean        4769.45
std        25478.09
min            0.00
1%            92.50
2%          1100.00
50%         3800.00
96%        11000.00
97%        12000.00
98%        14000.00
99%        16666.50
max     12666400.00
Name: average_salary, dtype: float64

In [ ]:
# EDA3: checking values in column "salary_maximum"
# checking 5% and 95% percentile data
# note: possible data mixed up between max and min salary. Avg salary is more relevant
# to use "average_salary" and drop "salary_maximum" and "salary_minimum" 
dfcopy["salary_maximum"].describe(percentiles=[0.05, 0.95, 0.99])

count    1048585.00
mean        5723.58
std        50183.87
min            0.00
5%          2010.00
50%         4500.00
95%        12000.00
99%        20000.00
max     25330000.00
Name: salary_maximum, dtype: float64

In [6]:
# EDA3: handling impossible values
# mask outliers in "average_salary" and "minimumYearsExperience"
dfcopy["average_salary"] = pd.to_numeric(dfcopy["average_salary"], errors="coerce")
dfcopy["average_salary"] = dfcopy["average_salary"].mask(
    (dfcopy["average_salary"] < 1100) |
    (dfcopy["average_salary"] > 20000)
)
dfcopy["minimumYearsExperience"] = pd.to_numeric(dfcopy["minimumYearsExperience"], errors="coerce")
dfcopy["minimumYearsExperience"] = dfcopy["minimumYearsExperience"].mask(
    (dfcopy["minimumYearsExperience"] > 20)
)
    
dfcopy[["average_salary", "minimumYearsExperience"]].describe()

       average_salary  minimumYearsExperience
count      1024402.00              1044322.00
mean          4668.32                    2.78
std           2736.25                    2.49
min           1100.00                    0.00
25%           3000.00                    1.00
50%           3850.00                    2.00
75%           5500.00                    4.00
max          20000.00                   20.00

In [ ]:
# EDA3: handling impossible values
# check after masking
dfcopy["minimumYearsExperience"].describe(percentiles=[0.01, 0.02, 0.96, 0.97, 0.98, 0.99])

count   1048585.00
mean          2.78
std           2.54
min           0.00
1%            0.00
2%            0.00
50%           2.00
96%           8.00
97%          10.00
98%          10.00
99%          10.00
max          88.00
Name: minimumYearsExperience, dtype: float64

In [ ]:
# EDA3: handling impossible values
# check after masking
print(f"median before masking: {df['average_salary'].median():>8,.2f}   after masking: {dfcopy['average_salary'].median():>8,.2f}")
print(f"mean   before masking: {df['average_salary'].mean():>8,.2f}   after masking: {dfcopy['average_salary'].mean():>8,.2f}")

median before masking: 3,800.00   after masking: 3,850.00
mean   before masking: 4,769.45   after masking: 4,668.32

In [7]:
# EDA3: handling impossible values
# fill NA data with its median then check result
dfcopy = dfcopy.fillna({
    "average_salary": dfcopy["average_salary"].median(),
    "minimumYearsExperience": dfcopy["minimumYearsExperience"].median()
})

print("Missing values in average_salary:", dfcopy["average_salary"].isna().sum())

print(f"Raw file:   {df['average_salary'].sum():,.2f}")
print(f"Cleaned:    {dfcopy['average_salary'].sum():,.2f}")
print(f"Difference: {df['average_salary'].sum() - dfcopy['average_salary'].sum():,.2f}")

print("\nMissing values in minimumYearsExperience:", dfcopy["minimumYearsExperience"].isna().sum())

print(f"Raw file:   {df['minimumYearsExperience'].sum():,.2f}")
print(f"Cleaned:    {dfcopy['minimumYearsExperience'].sum():,.2f}")
print(f"Difference: {df['minimumYearsExperience'].sum() - dfcopy['minimumYearsExperience'].sum():,.2f}")

Missing values in average_salary: 0
Raw file:   5,001,168,596.50
Cleaned:    4,859,990,569.00
Difference: 141,178,027.50

Missing values in minimumYearsExperience: 0
Raw file:   2,914,619.00
Cleaned:    2,906,993.00
Difference: 7,626.00

In [ ]:
# EDA4: navigate object data in "categories"
dfcopy["categories"].unique()

array(['[{"id":13,"category":"Environment / Health"},{"id":25,"category":"Manufacturing"},{"id":36,"category":"Sciences / Laboratory / R&D"}]',
       '[{"id":21,"category":"Information Technology"}]',
       '[{"id":33,"category":"Repair and Maintenance"}]', ...,
       '[{"id":2,"category":"Admin / Secretarial"},{"id":5,"category":"Banking and Finance"},{"id":20,"category":"Human Resources"},{"id":22,"category":"Insurance"},{"id":29,"category":"Professional Services"}]',
       '[{"id":8,"category":"Customer Service"},{"id":26,"category":"Marketing / Public Relations"},{"id":29,"category":"Professional Services"},{"id":33,"category":"Repair and Maintenance"},{"id":35,"category":"Sales / Retail"}]',
       '[{"id":3,"category":"Advertising / Media"},{"id":8,"category":"Customer Service"},{"id":9,"category":"Design"},{"id":21,"category":"Information Technology"},{"id":29,"category":"Professional Services"}]'],
      dtype=object)

In [ ]:
# EDA4: navigate object data in "categories"
dfcopy["categories"][0]

'[{"id":13,"category":"Environment / Health"},{"id":25,"category":"Manufacturing"},{"id":36,"category":"Sciences / Laboratory / R&D"}]'

In [8]:
# EDA4: navigate object data in "categories"
# import json module to parse the category string in the dataset
import json
# x = json.loads('{"id":13,"category":"Environment / Health"}')
# x["category"]

# to get only one category value - no explode
def parse_category(category_str):
    try:
        category_items = json.loads(category_str)
        # sorted_categories = sorted(category_items, key=lambda x: x.get("id")) # option 1: sort values then pick first one
        # return sorted_categories[0].get("category", None)                     # (not used)
        return category_items[0].get("category", None)                          # option 2: no sort values, pick first data 
    except (json.JSONDecodeError, TypeError):                                   # consideration: user input first data as dominant
        return None 
dfcopy["parsed_categories"] = dfcopy["categories"].apply(parse_category)

dfcopy["parsed_categories"].unique()

array(['Environment / Health', 'Information Technology',
       'Repair and Maintenance', 'Admin / Secretarial', 'Consulting',
       'Security and Investigation', 'Accounting / Auditing / Taxation',
       'Engineering', 'F&B', 'Telecommunications', 'Advertising / Media',
       'Marketing / Public Relations',
       'Real Estate / Property Management', 'Others', 'Customer Service',
       'General Work', 'Building and Construction', 'General Management',
       'Architecture / Interior Design', 'Logistics / Supply Chain',
       'Banking and Finance', 'Human Resources', 'Education and Training',
       'Events / Promotions', 'Manufacturing',
       'Healthcare / Pharmaceutical', 'Legal', 'Sales / Retail',
       'Social Services', 'Design', 'Professional Services',
       'Medical / Therapy Services', 'Personal Care / Beauty',
       'Risk Management', 'Purchasing / Merchandising', 'Entertainment',
       'Wholesale Trade', 'Insurance', 'Hospitality',
       'Sciences / Laboratory / R&D', 'Precision Engineering',
       'Public / Civil Service', 'Travel / Tourism'], dtype=object)

In [ ]:
# this result will be visualized using streamlit
# sum of metadata_totalNumberJobApplication and numberOfVacancies by parsed_categories
grouped = dfcopy.groupby("parsed_categories").agg(
    avg_salary=("average_salary", "median"),
    total_vacancy=("numberOfVacancies", "sum"),
    total_application=("metadata_totalNumberJobApplication","sum"),
    mean_min_exp=("minimumYearsExperience", "mean"),
).round(2).sort_values("avg_salary", ascending=False)

grouped["demand_ratio"] = grouped["total_application"] / grouped["total_vacancy"]
grouped["median_avg_salary"]=dfcopy["average_salary"].median()
grouped["median_min_years"]=dfcopy["minimumYearsExperience"].median()

grouped.reset_index().sort_values(["demand_ratio", "avg_salary"], ascending=False)

,parsed_categories,avg_salary,total_vacancy,total_application,mean_min_exp,demand_ratio,median_avg_salary,median_min_years
2,Risk Management,6500.00,1565,4193,4.60,2.68,3850.00,2.00
25,Social Services,3750.00,7793,17011,2.11,2.18,3850.00,2.00
22,Human Resources,3850.00,38029,82095,2.96,2.16,3850.00,2.00
20,Design,4000.00,13675,27044,2.76,1.98,3850.00,2.00
17,Marketing / Public Relations,4000.00,35671,70473,2.93,1.98,3850.00,2.00
23,Advertising / Media,3850.00,28713,53085,2.33,1.85,3850.00,2.00
32,Purchasing / Merchandising,3500.00,7009,12871,2.66,1.84,3850.00,2.00
1,Legal,6500.00,4767,8460,3.65,1.77,3850.00,2.00
18,Wholesale Trade,4000.00,4800,8324,3.12,1.73,3850.00,2.00
14,Real Estate / Property Management,4000.00,7976,13286,3.33,1.67,3850.00,2.00
3,Banking and Finance,6000.00,110853,175548,3.60,1.58,3850.00,2.00
6,Sciences / Laboratory / R&D,4900.00,14565,18048,1.87,1.24,3850.00,2.00
39,Admin / Secretarial,2900.00,229399,283872,1.74,1.24,3850.00,2.00
27,Accounting / Auditing / Taxation,3650.00,164882,197357,2.79,1.20,3850.00,2.00
36,Travel / Tourism,3250.00,2999,3497,2.69,1.17,3850.00,2.00
12,General Management,4150.00,41426,45584,3.66,1.10,3850.00,2.00
0,Information Technology,6750.00,236667,245810,4.05,1.04,3850.00,2.00
35,Logistics / Supply Chain,3250.00,93536,89650,2.36,0.96,3850.00,2.00
38,Hospitality,2975.00,15843,14697,2.45,0.93,3850.00,2.00
28,Events / Promotions,3600.00,13146,11614,2.09,0.88,3850.00,2.00
9,Engineering,4250.00,190675,167378,3.02,0.88,3850.00,2.00
13,Building and Construction,4100.00,159855,135375,3.74,0.85,3850.00,2.00
21,Others,3925.00,74232,59684,2.62,0.80,3850.00,2.00
4,Insurance,5250.00,7868,5719,3.17,0.73,3850.00,2.00
33,Manufacturing,3400.00,37304,24909,2.70,0.67,3850.00,2.00
7,Public / Civil Service,4500.00,2997,1938,2.15,0.65,3850.00,2.00
10,Professional Services,4250.00,13232,8443,3.15,0.64,3850.00,2.00
26,Precision Engineering,3750.00,1226,768,3.29,0.63,3850.00,2.00
8,Telecommunications,4250.00,2794,1742,3.18,0.62,3850.00,2.00
5,Consulting,5000.00,100884,61795,3.55,0.61,3850.00,2.00
19,Architecture / Interior Design,4000.00,29494,16514,3.27,0.56,3850.00,2.00
29,Sales / Retail,3550.00,99520,46046,2.46,0.46,3850.00,2.00
11,Entertainment,4150.00,6476,2987,2.69,0.46,3850.00,2.00
37,Customer Service,3100.00,240390,108853,1.86,0.45,3850.00,2.00
31,Environment / Health,3500.00,45651,17542,2.28,0.38,3850.00,2.00
34,Education and Training,3350.00,156371,58032,1.81,0.37,3850.00,2.00
24,Healthcare / Pharmaceutical,3750.00,168524,56098,2.07,0.33,3850.00,2.00
40,Repair and Maintenance,2800.00,18705,6134,2.18,0.33,3850.00,2.00
42,General Work,2500.00,52551,16119,1.85,0.31,3850.00,2.00
16,Medical / Therapy Services,4000.00,12696,3789,2.02,0.30,3850.00,2.00
30,F&B,3500.00,244260,49465,2.78,0.20,3850.00,2.00
41,Security and Investigation,2700.00,32768,6129,1.39,0.19,3850.00,2.00
15,Personal Care / Beauty,4000.00,38466,2398,2.92,0.06,3850.00,2.00

In [ ]:
# this result will be visualized using streamlit
grouped_final = grouped.loc[
    (grouped["demand_ratio"] < 1) &
    (grouped["avg_salary"] >= grouped["median_avg_salary"]) &
    (grouped["mean_min_exp"] <= grouped["median_min_years"])
]

grouped_final

Empty DataFrame
Columns: [avg_salary, total_vacancy, total_application, mean_min_exp, demand_ratio, median_avg_salary, median_min_years]
Index: []

In [ ]:
# export dfcopy to parquet
dfcopy.to_parquet('dfcopy.parquet', index=False)

In [12]:
%%writefile app.py
# --- Part 2: Streamlit ---
from pathlib import Path  
import pandas as pd
import streamlit as st  
import plotly.express as px

st.set_page_config(page_title="Singapore Job Market Dashboard", layout="wide")  

@st.cache_data
def load_data():    
    DATA_PATH = Path(__file__).resolve().parent / "dfcopy.parquet"    
    df = pd.read_parquet(DATA_PATH)
    
    # 1. Standardize temporal parsing utilizing metadata_newPostingDate
    if "metadata_newPostingDate" in df.columns:
        df["posted_date"] = pd.to_datetime(df["metadata_newPostingDate"], errors='coerce')
    elif "metadata_postedCompany_postedDate" in df.columns:
        df["posted_date"] = pd.to_datetime(df["metadata_postedCompany_postedDate"], errors='coerce')
    else:
        df["posted_date"] = pd.to_datetime(df["metadata_createdAt"], errors='coerce')

    # 2. Map raw position levels into five standardized career segments
    position_mapping = {
        "Fresh/entry level": "Entry",
        "Non-executive": "Entry",
        "Junior Executive": "Junior",
        "Executive": "Mid",
        "Professional": "Mid",
        "Senior Executive": "Senior",
        "Manager": "Management",
        "Middle Management": "Management",
        "Senior Management": "Management",
    }
    if "positionLevels" in df.columns:
        df["seniority_level"] = df["positionLevels"].map(position_mapping).fillna("Mid")
    else:
        df["seniority_level"] = "Mid"
        
    # 3. Drop raw metadata columns safely using errors='ignore'
    columns_to_drop = [
        "categories", "metadata_isPostedOnBehalf", "metadata_jobPostId", 
        "metadata_repostCount", "metadata_totalNumberOfView", 
        "salary_maximum", "salary_minimum"
    ]
    df = df.drop(columns=[col for col in columns_to_drop if col in df.columns], errors='ignore')
    
    return df  

try:
    df = load_data()
except Exception as e:
    st.error(f"Error reading dfcopy.parquet from directory: {e}")
    st.stop()

st.title("Singapore Job Market Dashboard")  

# ---------------------------------------------------------------------------
# Global Sidebar Filters
# ---------------------------------------------------------------------------
with st.sidebar:    
    st.header("Filters")    
    category_options = sorted(df["parsed_categories"].dropna().unique())    
    selected_categories = st.multiselect(        
        "Category", category_options, default=category_options    
    )  

    employment_options = sorted(df["employmentTypes"].dropna().unique()) if "employmentTypes" in df.columns else []
    selected_employment = st.selectbox("Employment Type", ["All"] + employment_options)  

    open_only = st.checkbox("Show only open postings", value=False)  

    min_exp = int(df["minimumYearsExperience"].min()) if "minimumYearsExperience" in df.columns else 0
    max_exp = int(df["minimumYearsExperience"].max()) if "minimumYearsExperience" in df.columns else 15
    experience_range = st.slider(        
        "Minimum Years Experience", min_exp, max_exp, (min_exp, max_exp)    
    )  

# Filter operations
if selected_categories:
    df = df[df["parsed_categories"].isin(selected_categories)]
if selected_employment != "All":    
    df = df[df["employmentTypes"] == selected_employment]
if open_only and "status_jobStatus" in df.columns:    
    df = df[df["status_jobStatus"] == "Open"]
if "minimumYearsExperience" in df.columns:
    df = df[df["minimumYearsExperience"].between(*experience_range)]

# ---------------------------------------------------------------------------
# Layout Tabs
# ---------------------------------------------------------------------------
tab_overview, tab_drilldown, tab_trends, tab_recommender = st.tabs([
    "📊 Overview", 
    "🔍 Drill-Down View", 
    "📈 Time Trend View",
    "⭐ Career Recommender",
])

# Tab 1: Overview
with tab_overview:
    st.header("Overview")  
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Postings", f"{len(df):,.0f}")
    col2.metric(
        "Average Salary",
        f"${df['average_salary'].median():,.0f}" if len(df) and 'average_salary' in df.columns else "N/A",
    )
    applicants = df["metadata_totalNumberJobApplication"].sum() if "metadata_totalNumberJobApplication" in df.columns else 0
    col3.metric("Total Applications", f"{int(applicants):,.0f}")  

    st.write("---")
    c1, c2 = st.columns(2)
    with c1:
        st.subheader("Top Roles Based on Categories")
        if len(df) > 0 and "parsed_categories" in df.columns:
            top_cats = df["parsed_categories"].value_counts().head(10).reset_index()
            top_cats.columns = ["Category", "Postings"]
            fig_cats = px.bar(top_cats, x="Postings", y="Category", orientation="h", template="plotly_white")
            fig_cats.update_layout(yaxis={'categoryorder': 'total ascending'})
            st.plotly_chart(fig_cats, use_container_width=True)
    with c2:
        st.subheader("Average Salary by Categories")
        if len(df) > 0 and "average_salary" in df.columns and "parsed_categories" in df.columns:
            cat_sal = df.groupby("parsed_categories")["average_salary"].median().reset_index()
            cat_sal.columns = ["Category", "Median Salary"]
            cat_sal = cat_sal.sort_values(by="Median Salary", ascending=False).head(10)
            fig_sal = px.bar(cat_sal, x="Median Salary", y="Category", orientation="h", template="plotly_white")
            fig_sal.update_layout(yaxis={'categoryorder': 'total ascending'})
            st.plotly_chart(fig_sal, use_container_width=True)

# Tab 2: Drill-Down View
with tab_drilldown:
    st.header("Drill-Down View")
    dd_level = st.selectbox("Position Level", ["All"] + sorted(df["seniority_level"].dropna().unique()))
    df_dd = df.copy()
    if dd_level != "All":
        df_dd = df_dd[df_dd["seniority_level"] == dd_level]
        
    dd_category = st.selectbox("Category Focus", ["All"] + sorted(df_dd["parsed_categories"].dropna().unique())[:100])
    if dd_category != "All":
        df_dd = df_dd[df_dd["parsed_categories"] == dd_category]
        
    st.dataframe(df_dd[["title", "parsed_categories", "seniority_level", "average_salary", "minimumYearsExperience"]].head(50), use_container_width=True)

# Tab 3: Time Trend View
with tab_trends:
    st.header("Time Trend View")
    if len(df) > 0 and "posted_date" in df.columns and not df["posted_date"].isna().all():
        df_ts = df.dropna(subset=["posted_date"]).copy()
        df_ts["Month"] = df_ts["posted_date"].dt.to_period("M").astype(str)
        ts_grouped = df_ts.groupby("Month").size().reset_index(name="Postings")
        
        fig_trend = px.line(ts_grouped, x="Month", y="Postings", title="Postings Over Time", markers=True, template="plotly_white")
        st.plotly_chart(fig_trend, use_container_width=True)
    else:
        st.info("No time trend metrics available for the filtered dataset. Verify that metadata_newPostingDate contains valid date components.") 

# Tab 4: Career Recommender
with tab_recommender:
    st.header("⭐ Career Recommender")
    st.markdown(
        "Tell us where you are and what you care about. We score all "
        f"\*\*{len(df):,.0f} career tracks\*\* (category × seniority) on four dimensions and rank them "
        "for \*you\* — with every component of the score shown, so you can disagree with it."
    )

    SENIORITY_ORDER = ["Entry", "Junior", "Mid", "Senior", "Management"]  
    st.markdown("### 1. Your situation")  

    c1, c2, c3 = st.columns([1, 1, 2])
    with c1:    
        years = st.number_input(
            "Years of relevant experience", min_value=0, max_value=25, value=3, step=1
        )
    with c2:    
        target_salary = st.number_input(
            "Minimum monthly salary you need (SGD)",
            min_value=1000,
            max_value=20000,
            value=4000,
            step=250,
        )
    with c3:    
        levels = st.multiselect(
            "Seniority levels you would consider",
            options=SENIORITY_ORDER,
            default=SENIORITY_ORDER,
            help="Leave all selected if you are open to anything.",
        )  

    interests = st.multiselect(
        "Restrict to these fields (optional)",
        options=sorted(df["parsed_categories"].dropna().unique()),
        default=[],
        placeholder="All fields — leave empty if you are exploring",
    )

    st.markdown("### 2. Customize Scoring Weights")
    st.caption("Adjust preferences below. The aggregate total must sum to exactly 100%.")
    w_col1, w_col2, w_col3, w_col4 = st.columns(4)
    with w_col1:
        w_demand = st.slider("Demand Weight (%)", 0, 100, 30, step=5) / 100.0
    with w_col2:
        w_comp = st.slider("Compensation Weight (%)", 0, 100, 35, step=5) / 100.0
    with w_col3:
        w_exp = st.slider("Experience Fit Weight (%)", 0, 100, 20, step=5) / 100.0
    with w_col4:
        w_pop = st.slider("Popularity Weight (%)", 0, 100, 15, step=5) / 100.0

    total_weight = w_demand + w_comp + w_exp + w_pop
    if not (0.99 <= total_weight <= 1.01):
        st.warning(f"⚠️ Your current allocation sums to {int(total_weight * 100)}%. Please rebalance sliders to equal exactly 100%.")

    df_rec = df.copy()
    if interests:
        df_rec = df_rec[df_rec["parsed_categories"].isin(interests)]
    if levels:
        df_rec = df_rec[df_rec["seniority_level"].isin(levels)]

    if len(df_rec) > 0 and "average_salary" in df_rec.columns:
        grouped = df_rec.groupby(["parsed_categories", "seniority_level"]).agg(
            median_salary=("average_salary", "median"),
            job_postings=("average_salary", "count"),   # to count how many posting occurence (rows)
            avg_exp=("minimumYearsExperience", "mean") if "minimumYearsExperience" in df_rec.columns else ("average_salary", lambda x: 0),
            total_apps=("metadata_totalNumberJobApplication", "sum") if "metadata_totalNumberJobApplication" in df_rec.columns else ("average_salary", lambda x: 0)
        ).reset_index()
        
        max_posts = grouped["job_postings"].max() if grouped["job_postings"].max() > 0 else 1
        max_apps = grouped["total_apps"].max() if grouped["total_apps"].max() > 0 else 1
        
        # -------------------------------------------------------------------------------------------------------------------------------------------
        # What It Does: This calculation applies a min-max relative scale to the absolute volume of job advertisements within a single career track. 
        # The category-seniority track containing the single highest concentration of vacancies (max_posts) receives a baseline score of 100%, and 
        # all other tracks are graded proportionally down to 0%.
        # -------------------------------------------------------------------------------------------------------------------------------------------   
        grouped["Demand_Score"] = (grouped["job_postings"] / max_posts) * 100
        
        # -------------------------------------------------------------------------------------------------------------------------------------------
        # What It Does: This functions as a one-sided satisficing filter. If a career track's median market salary meets or exceeds 
        # the user's input (target_salary), it receives a perfect score of 100%. If it falls short, the score degrades linearly based on how close 
        # the median pay is to the user's target threshold.
        # -------------------------------------------------------------------------------------------------------------------------------------------
        grouped["Comp_Score"] = grouped["median_salary"].apply(lambda s: 100 if s >= target_salary else (s / target_salary) * 100)
        
        # -------------------------------------------------------------------------------------------------------------------------------------------
        # What It Does: If a track's average requirement is less than or equal to the candidate's current experience level (years), it receives a 
        # 100% score. If the track demands more experience than the user possesses, it applies a sharp penalty—losing 25% for every year of missing 
        # experience, bottoming out at 0%.
        # -------------------------------------------------------------------------------------------------------------------------------------------
        grouped["Exp_Score"] = grouped["avg_exp"].apply(lambda e: 100 if e <= years else max(0, 100 - (e - years) * 25))
        
        # -------------------------------------------------------------------------------------------------------------------------------------------
        #  What It Does: This normalizes total job application volume across all domains against the single most competitive track in Singapore's 
        # job market (max_apps).
        # -------------------------------------------------------------------------------------------------------------------------------------------
        grouped["Popularity_Score"] = (grouped["total_apps"] / max_apps) * 100
        
        grouped["Score"] = (grouped["Demand_Score"] * 0.3 + grouped["Comp_Score"] * 0.35 + grouped["Exp_Score"] * 0.2 + grouped["Popularity_Score"] * 0.15)
        ranked = grouped.sort_values(by="Score", ascending=False).head(10)
        
        st.markdown("### 🎯 Recommended Career Tracks Match Matrix")
        st.dataframe(
            ranked.style.format({
                "median_salary": "SGD ${:,.0f}",
                "avg_exp": "{:.1f} yrs",
                "Score": "{:.1f}%",
                "Demand_Score": "{:.1f}%",
                "Comp_Score": "{:.1f}%",
                "Exp_Score": "{:.1f}%",
                "Popularity_Score": "{:.1f}%"
            }),
            use_container_width=True,
            hide_index=True
        )
        
        if not ranked.empty:
            top_track = ranked.iloc[0]
            st.success(f"💡 **Conclusive Recommendation:** Based on your personalized criteria weights, your optimal choice is the **{top_track['parsed_categories']}** sector at the **{top_track['seniority_level']}** level, achieving a high compatibility score of **{top_track['Score']:.1f}%** (Median Salary: SGD {top_track['median_salary']:,.0f}, Active Postings: {top_track['job_postings']}).")
    else:
        st.info("No matching configuration records available for recommendation parameters.")

Overwriting app.py